### ISSUE TITLE
Issue with info in History tab after sending to integrated addresses

### ISSUE THREAD

**Issue by minerkid** [hyle-team/zano#152]
After sending coins to integrated address, the tx shown the history tab  has the base address it was sent to and not the full integrated address. hope this makes sense
![image](https://user-images.githubusercontent.com/37032313/72462440-b20c6400-3796-11ea-9af1-5ba28c2cf679.png)
 
as picture shows you can see the normal "Z" address without the "i"

**Comment by sowle** [comment]
Sending to an integrated address is the very same as sending to standard address with payment id and we can't determine which option was used because of both of them lead to the same result.
If someone sent coins to a standard address with payment id specified should we display an integrated address instead? I think no.

**Comment by cryptozoidberg** [comment]
@sowle, to my knowledge, payment_id itself is not used anymore, it's only used with integrated address now.

**Comment by sowle** [comment]
I eventually fix it. Additionally, coretest wallet_sending_to_integrated_address was added to cover this case

Now if tx_receiver is set to extra and payment ID is also present, the receiver address will be shown as integrated, not as normal + payment ID.

**Comment by Andreevsky** [comment]
Works fine at v1.1.7.94[32f5881]
