### ISSUE TITLE
Consider eliminating or restricting periods on alias's to preventing phishing attacks

### ISSUE THREAD

**Issue by blackholebrowsing** [hyle-team/zano#186]
I'm new to contributing on GitHub, so forgive me if the format isn't correct. I want to try and contribute here a bit.

Something I realized with alias's is that someone can do a phishing attack on all the current names. By simply adding a period at the end. This is especially problematic as the way the dropdown menu works when typing in a receiver.

Gigabyted (original)
Gigabyted. (the easiest one to overlook)
Giga.byted
Gigabyted-
Gigabyte.d
You can see how this is potentially problematic. 

Otherwise someone can literally copy all the usernames in the network and add a period at the end and wait for people to accidentally send money there. Its a very cheap method as well, as alias's are only 0.12 Zano to register right now

It would be better to prevent that from happening than to roll-back/undo a supposedly decentralized alias based system. 

I won't go so far as to say to eliminate periods, that's up to you, but at minimum restrict their use. 

ICANN doesn't allow periods in their system, and there was good reasons for that, as you can make it look like something it is not.

Idea: Don't allow registration formats with a hyphen or period at the beginning or end of an alias.

**Comment by blackholebrowsing** [comment]
This is not a GUI glitch, it was approved on the network level. Just registered "alias."

**Comment by cryptozoidberg** [comment]
@blackholebrowsing  thanks for the reporting that!

At this moment symbols allowed for aliases are: 

https://github.com/hyle-team/zano/blob/dc3c52ea73ad6d4f9af1c404e7acbf84a2a7cc46/src/currency_core/currency_format_utils.cpp#L1726


I left "-" as a potential delimiter option, since some nicknames consist of two words, like "crypto-zoidberg", and it looks more readable I believe. And "." left for those who are willing to register aliases for websites. This was like that since Boolberry launch.

If the community believes that those symbols are still big risk, we can get rid of them with the next hard fork. 
Please comment below.
