### ISSUE TITLE
Linux GUI: empty window on startup "Your file was not found"

### ISSUE THREAD

**Issue by anonimal** [hyle-team/zano#19]
On Ubuntu Bionic (gcc 8.2.0/clang 7.0.0) and Arch Linux (gcc 8.2.1/clang 7.0.1), Qt5, running target `make gui` in #15 (perhaps #15 needs much more updating), running the `Zano` binary. Screenshot attached.

![zano-gui](https://user-images.githubusercontent.com/12156341/53780130-db176380-3efa-11e9-8fcb-484e436ee290.png)

**Comment by anonimal** [comment]
Note: X'ing out to close the window/application has no effect. I'm assuming this is related to the implementation of `MainWindow::closeEvent(QCloseEvent *event)` where the branch leads to `event->ignore()`? I haven't thrown this under a debugger.

**Comment by cryptozoidberg** [comment]
Thanks for the report! When the main GUI binary is getting launched it expects to have "html" subfolder with the actual layout for rendering. Also, instead of copying html every time, for example, if you work in dev tree, and html files located somewhere else, then it's possible to specify this path by "--html-path=/some/path/html".
Let me know if this helped or not with this issue. And reopen please if it's not helped.
