### ISSUE TITLE
If click wallet setting button GUI freeze during restore from backup

### ISSUE THREAD

**Issue by Andreevsky** [hyle-team/zano#203]
![zan](https://user-images.githubusercontent.com/16042035/87858646-17086880-c938-11ea-9974-621f57bdf37d.png)

After syncronization finish app become well respondable again.
To reproduce:
1. Click Add and Restore from backup buttons.
2. Start restote some wallet from seed. Better to use wallet with a lot of transactions.
3. During syncronising process click button wallet setting (in the right up corner).

Win 10 2004
v1.1.7.94[32f5881]

**Comment by sowle** [comment]
Seems to be fixed as the wallet doesn't lock up anymore in this case, but still Front-end should properly handle "CORE_BUSY" return code when calling, otherwise we're having this:
<img width="597" alt="image" src="https://user-images.githubusercontent.com/29127158/90132909-46639700-dd77-11ea-8689-64d5f71ef893.png">
