### ISSUE TITLE
Add the ability to change blockchain save location

### ISSUE THREAD

**Issue by VoidXH** [hyle-team/zano#277]
The blockchain takes up a large chunk of the main drive, which might be an issue for some. The ability to change blockchain save location would be a solution to this.

**Comment by cryptozoidberg** [comment]
Agreed, will implement it after atomics got done

**Comment by cryptozoidberg** [comment]
So, after reviewing this problem in more depth, we came to understanding that having setting in UI might confuse people, since changing location in UI won't actually move existing database to new location, in that case it's likely possible that users would have two copies of databases in different locations. 
Instead, we decided to suggest using command line option "--data-dir="some\path\here", or, if command line option is not suitable for some reason, there are also option to create Zano.conf file in default location(same as "html" folder located), and use it as a configuration file where configuring done by adding options, named same way as command line options. For example, putting into this file this text: 
```
data-dir="E:\home\temp\data_dir"
```
will have same affect as providing --data-dir="E:\home\temp\data_dir" in command line. 
More details about writing .conf files could be read at boost documentation: https://www.boost.org/doc/libs/1_79_0/doc/html/program_options/overview.html#id-1.3.30.5.10.2

More info about command line options could be fetched with providing --help command line option.
