### ISSUE TITLE
ZANO not working with CPU

### ISSUE THREAD

**Issue by Darth2Jedi** [hyle-team/zano#278]
I am unable to get the miner working with a CPU.

Please advise on what needs correcting.

![Zano CPU error 2021-03-05 203836](https://user-images.githubusercontent.com/80128594/110170963-d1f25300-7daf-11eb-9220-413dabe0e6ef.png)

I have an Intel I59400 6core cpu

Thanks

**Comment by cryptozoidberg** [comment]
@sowle  can you take a look into this?

**Comment by sowle** [comment]
@Darth2Jedi please, try adding `--cpu` to your command line
<img width="1106" alt="image" src="https://user-images.githubusercontent.com/29127158/111488077-f6ecab80-8749-11eb-84c5-c821fa4eda50.png">

**Comment by Estacaco** [comment]
So you have to tell the CPU only miner to turn on the CPU? why? that seesm pointless and just creates problems like this, over and over. can you guess how I found this issue post?

**Comment by sowle** [comment]
> why?
Technically speaking there's no such thing as "CPU only miner". According to the forked sources ( https://github.com/hyle-team/progminer ) one could configure miner software to support CPU, CUDA, or OpenCL in various combinations.

For convenience, I decided to build three different binaries from the very same sources for these three different build options, otherwise, a person who wants the only CPU or only CUDA would experience issues with GPU libs dependencies.
No one wants issues with dependencies.

That's why each miner requires these command-line options.

But I agree that this looks pointless and we'll think about how to improve this.

Thank you.
