### ISSUE TITLE
Implement time check on connection and proper behaviour in case of time missmatch. 

### ISSUE THREAD

**Issue by Andreevsky** [hyle-team/zano#50]
**Description**
Add using of NTP from public servers in case of average delta network is different from current node.

**Environment**
testnet builds 1.0.39[02b85f2]

**Attachments**
[Zano.zip](https://github.com/hyle-team/zano/files/3436299/Zano.zip)

**Comment by Andreevsky** [comment]
1. Wrong time notification have a delay of 30 sec - 1m until it displays after application run.
2. After application run with wrong time it is possible to send succesfull transaction. It doesn't display on wallet history screen until application relaunch with correct time set. 
3.  Application freezes sometimes when closing with wrong system time set. (log included)
4. Notification of wrong time doesn't display if change time during application work. (run with correct time and change after)
5. Notification doesn't disapear if run with wrong time and then change to correct time.
6. If setup of winter/summer time is set off and result time is incorrect then notification message still doesn't display.
7. time zone setting doesn't affect notification message displaying

**Comment by sowle** [comment]
1 -- it's ok, may take up to 10 min depending on connections count and p2p conversation flow
2 -- should be okay in build > 57
3 -- was fixed by 77235ce0727d56372d952e7daa5e6b22a5bc7bd7 
4 -- I checked both in Zano and zanod, works okay. Please, see build > 57
5 -- The same as above, check out build > 57
6 -- summer saving time should not affect time sync behavior, I can't see it happens
7 -- this is okay
